name: bedtime_story_player
description: A bedtime story audio player app for mobile devices.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
